[tool.poetry]
name = "chessstats"
version = "0.1.0"
description = "Package that can turn a pgn file into chess insights"
authors = ["jaco <jaco@mediadistillery.com>"]

[tool.poetry.dependencies]
python = "^3.8"
parsita = "^1.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
